### ISSUE TITLE
Feature request: support VolumeSnapshot

### ISSUE THREAD

**Issue by aledbf** [ThinkParQ/beegfs-csi-driver#12]
:wave: Hi, are there any plans to add support for snapshots?
Thanks!

**Comment by ckrizek** [comment]
Hi @aledbf .

We currently have no plans of adding support for snapshots. This is because BeeGFS does not support snapshots and has no roadmap for implementing them. The BeeGFS CSI driver functionality is highly dependent on the BeeGFS filesystem capabilities so snapshot functionality would only be added to the CSI driver if that functionality was added to the BeeGFS filesystem itself.

**Comment by aledbf** [comment]
@ckrizek thank you
