### ISSUE TITLE
Plans for supporting K8s 1.23.x and 1.24.x

### ISSUE THREAD

**Issue by klis** [ThinkParQ/beegfs-csi-driver#4]
Hi,

I was wondering about plans to support newer versions of K8s. Are there plans to support beegfs 7.1.5 on the K8s version 1.23.x and other versions since 1.24 is planned for April?

**Comment by ejweber** [comment]
Hello @klis,

We plan to release a new version near the end of April that will support Kubernetes v1.23. Our general cadence is a new minor or patch release every 3-4 months. We test on any the latest versions of Kubernetes that can be deployed into our test infrastructure with [Kubespray](https://github.com/kubernetes-sigs/kubespray/releases). Kubespray tends to lag behind the latest version of Kubernetes by a few months itself, so we don't tend to support Kubernetes versions right on release.

See https://github.com/NetApp/beegfs-csi-driver#support-policy for a bit more detail.

That being said, we haven't had to modify anything about the driver or its deployment manifests to make it work with a specific Kubernetes version since Kubernetes v1.19 released, so it is likely the current version can be deployed on Kubernetes v1.23 (and soon on Kubernetes v1.24). We simply can't provide any guarantees.

**Comment by klis** [comment]
@ejweber thanks for the quick response. And since we are talking about versions, will v1.2.1 work on K8s 1.22.7? I see that you support 1.22.3 but since this is the minor version I'm thinking to upgrade all the way to K8s v1.22.7.

**Comment by ejweber** [comment]
It was difficult to formulate when writing the policy I linked earlier, but we are generally supportive of running on the latest patch version of a Kubernetes minor version (i.e. we would prefer 1.22.7 over 1.22.3). We capture the specific patch version tested for two reasons:

1. It is theoretically possible (though unlikely) that a Kubernetes patch will break functionality, and we want to have a record of which exact version we know works.
2. We know for a fact that some old Kubernetes patch versions had issues (e.g. 1.22.0 had [this issue](https://github.com/NetApp/beegfs-csi-driver/blob/master/docs/troubleshooting.md#missing-vol_datajson)).

**Comment by klis** [comment]
Thanks for the info.
